site_name: GH Dashboard
site_url: https://lambdasistemi.github.io/gh-dashboard/docs/
repo_url: https://github.com/lambdasistemi/gh-dashboard
repo_name: lambdasistemi/gh-dashboard

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

nav:
  - Navigation: index.md

docs_dir: docs
site_dir: dist/docs

plugins:
  - search

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
